### PR TITLE
Exception handling

### LINKED ISSUE #17: Handling of exceptions
Now the behavior of the application is incorrect if we send requests with incorrect input parameters.
For example: 
Send http request GET http://localhost:8080/api/projects/111
actual result: server returns 500 responce code (Internal server error). Error is appeared on server logs with stack trace
expected result: server returns 404 responce code with message: "Project with id='111' not found". No error is appeared on server logs.

### PR DESCRIPTION
**Pull request by DOGGER152**

### CODE REVIEW

File: src/main/java/com/springweb/dv_spring_web_mongo/service/ProjectService.java [hunk 1]
```diff
@@ -26,25 +23,33 @@
         for (Project project : list) {
             listWithDto.add(project.convertToDTO());
         }
-        return listWithDto;
+        if (listWithDto.isEmpty()) throw new ProjectNotFoundException("Database of projects is empty");
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/service/ProjectService.java]: empty list of projects is not an error. The database can be empty

File: src/main/java/com/springweb/dv_spring_web_mongo/service/ProjectService.java [hunk 2]
```diff
@@ -26,25 +23,33 @@
...
+        else return listWithDto;
     }
 
     public ProjectDTO getProjectById(String id) {
-        Optional<Project> project = projectRepository.findById(id);
-        return project.get().convertToDTO();
+        Optional<Project> optional = projectRepository.findById(id);
+        if(optional.isEmpty()) throw new ProjectNotFoundException("Project with id '" + id + "' not found");
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/service/ProjectService.java]: please format whole file

File: src/main/java/com/springweb/dv_spring_web_mongo/service/ProjectService.java [hunk 3]
```diff
@@ -26,25 +23,33 @@
...
 
     public void addNewProject(ProjectDTO projectDTO) {
         projectRepository.save(projectDTO.convertToProject());
     }
 
     public void changeProjectName(ProjectDTO projectDTO, String id) {
-        Project project = projectRepository.findById(id).get();
-        project.setProjectName(projectDTO.getProjectName());
-        projectRepository.save(project);
+        Optional<Project> optional = projectRepository.findById(id);
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/service/ProjectService.java]: the code is repeated several times:
```java
Optional<Project> optional = projectRepository.findById(id);
        if (optional.isEmpty()) throw new ProjectNotFoundException("Project with id '" + id + "' not found");
```
can you create new method with signature `private Project getById(String projectId)` and use?

File: src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/ProjectNotFoundException.java [hunk 4]
```diff
@@ -0,0 +1,5 @@
+package com.springweb.dv_spring_web_mongo.exception_handling;
+
+public class ProjectNotFoundException extends RuntimeException{
+    public ProjectNotFoundException(String message){super(message);}
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/ProjectNotFoundException.java]: please format

File: src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/ProjectIncorrectData.java [hunk 5]
```diff
@@ -0,0 +1,13 @@
+package com.springweb.dv_spring_web_mongo.exception_handling;
+
+import lombok.AccessLevel;
+import lombok.AllArgsConstructor;
+import lombok.Data;
+import lombok.NoArgsConstructor;
+
+@Data
+@NoArgsConstructor(access = AccessLevel.PUBLIC)
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/ProjectIncorrectData.java]: you can remove `access = AccessLevel.PUBLIC` besause the value is PUBLIC by default

**Review by iv21dk — CHANGES_REQUESTED** [review]

File: src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/ProjectNotFoundException.java [hunk 6]
```diff
@@ -0,0 +1,5 @@
+package com.springweb.dv_spring_web_mongo.exception_handling;
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/ProjectNotFoundException.java]: please move the class to the package: `com.springweb.dv_spring_web_mongo.exception`

File: src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/GlobabExceptionHandler.java [hunk 7]
```diff
@@ -0,0 +1,18 @@
+package com.springweb.dv_spring_web_mongo.exception_handling;
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/GlobabExceptionHandler.java]: please rename the package: `com.springweb.dv_spring_web_mongo.exception.handling`

File: src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/ProjectIncorrectData.java [hunk 8]
```diff
@@ -0,0 +1,13 @@
+package com.springweb.dv_spring_web_mongo.exception_handling;
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/ProjectIncorrectData.java]: please rename the package: `com.springweb.dv_spring_web_mongo.exception.handling`

File: src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/GlobabExceptionHandler.java [hunk 9]
```diff
@@ -0,0 +1,18 @@
...
+import org.springframework.web.bind.annotation.ExceptionHandler;
+
+@ControllerAdvice
+public class GlobabExceptionHandler {
+
+    @ExceptionHandler
+    ResponseEntity<ProjectIncorrectData> handleException(ProjectNotFoundException ex) {
+        ProjectIncorrectData projectIncorrectData = new ProjectIncorrectData();
+        projectIncorrectData.setErrorMessage(ex.getMessage());
+        return new ResponseEntity<>(projectIncorrectData, HttpStatus.NOT_FOUND);
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/GlobabExceptionHandler.java]: The solution is possible too, and there is another way: you can just add the annotation `@ResponseStatus(HttpStatus.NOT_FOUND)` in the `ProjectNotFoundException` class. So this exception handler will not needed

**Review by iv21dk — CHANGES_REQUESTED** [review]

File: src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/GlobabExceptionHandler.java (hunk 9 above)
Comment (iv21dk) [reply src/main/java/com/springweb/dv_spring_web_mongo/exception_handling/GlobabExceptionHandler.java]: Agreed to leave as is

File: src/main/java/com/springweb/dv_spring_web_mongo/service/ProjectService.java [hunk 10]
```diff
@@ -30,21 +27,30 @@
     }
 
     public ProjectDTO getProjectById(String id) {
-        Optional<Project> project = projectRepository.findById(id);
-        return project.get().convertToDTO();
+        checkProjectNotNull(id);
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/service/ProjectService.java]: For now you request one object twice from database. It is not good

File: src/main/java/com/springweb/dv_spring_web_mongo/service/ProjectService.java [hunk 11]
```diff
@@ -30,21 +27,30 @@
...
         project.setProjectName(projectDTO.getProjectName());
         projectRepository.save(project);
     }
 
     public void deleteProject(String id) {
+        checkProjectNotNull(id);
         projectRepository.deleteById(id);
     }
+
+    public void checkProjectNotNull(String id) {
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/service/ProjectService.java]: Please return `Project` here and rename to `getById`. And you can use the method instead of repeated retrieving data in the several methods

**Review by iv21dk — CHANGES_REQUESTED** [review]

File: src/main/java/com/springweb/dv_spring_web_mongo/service/ProjectService.java [hunk 12]
```diff
@@ -30,21 +27,30 @@
     }
 
     public ProjectDTO getProjectById(String id) {
-        Optional<Project> project = projectRepository.findById(id);
-        return project.get().convertToDTO();
+        getById(id);
+        return projectRepository.findById(id).get().convertToDTO();
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/service/ProjectService.java]: Why you cannot use `getById(id)` instead of `projectRepository.findById(id).get()`?

**Review by iv21dk — CHANGES_REQUESTED** [review]

**Comment by iv21dk** [comment]
Approved
