### PR TITLE
Validation dto object

### LINKED ISSUE #19: Validation of dto objects before processing
We need to check that client sent correct request body for methods:
* POST /api/projects
* PUT /api/projects/{project-id}

The body is considered as correct if the field "projectName" is filled (not null and not empty string). 
If the request body is incorrect, server should return code 400 with message like "the property 'projectName' is not defined"

### PR DESCRIPTION
**Pull request by DOGGER152**

### CODE REVIEW

File: src/main/java/com/springweb/dv_spring_web_mongo/dto/ProjectDTOGet.java [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+import org.hibernate.validator.constraints.NotEmpty;
+import org.springframework.data.annotation.Id;
+import org.springframework.data.mongodb.core.mapping.Document;
+
+import javax.validation.constraints.NotNull;
+
+@NoArgsConstructor
+@AllArgsConstructor
+@Data
+public class ProjectDTOGet {
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/dto/ProjectDTOGet.java]: Please rename to `ProjectDTO`

File: src/main/java/com/springweb/dv_spring_web_mongo/dto/ProjectDTOGet.java [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+    @Id
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/dto/ProjectDTOGet.java]: What is the reason to add `@Id` annotation?

File: src/main/java/com/springweb/dv_spring_web_mongo/dto/ProjectDTOSend.java [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+import lombok.Data;
+import lombok.NoArgsConstructor;
+import org.springframework.data.annotation.Id;
+
+import javax.validation.constraints.NotNull;
+
+@Data
+@NoArgsConstructor
+@AllArgsConstructor
+public class ProjectDTOSend {
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/dto/ProjectDTOSend.java]: Please rename to `ProjectCreateOrUpdateDTO`

File: src/main/java/com/springweb/dv_spring_web_mongo/dto/ProjectDTOSend.java [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+
+    @Id
+    String id;
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/dto/ProjectDTOSend.java]: `id` field is unused in fact you can remove it

File: src/main/java/com/springweb/dv_spring_web_mongo/dto/ProjectDTOSend.java [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+
+    @NotNull
+    String projectName;
+
+    public Project convertToProject() {
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/dto/ProjectDTOSend.java]: The method is never used

**Review by iv21dk — CHANGES_REQUESTED** [review]

File: src/main/java/com/springweb/dv_spring_web_mongo/model/Project.java [hunk 6]
```diff
@@ -28,4 +23,8 @@
     public ProjectDTO convertToDTO() {
         return new ProjectDTO(this.id, this.projectName);
     }
+
+    public ProjectCreateOrUpdateDTO convertToDTOSend() {
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/model/Project.java]: The method is used only from tests. It doesn't make sense to keep it here. Why you cannot just create new instance in the test?

File: src/main/java/com/springweb/dv_spring_web_mongo/controller/ProjectController.java [hunk 7]
```diff
@@ -27,13 +29,13 @@ public ProjectDTO findProjectById(@PathVariable String id) {
     }
 
     @PostMapping()
-    public void addNewProject(@RequestBody ProjectDTO projectDTO) {
-        projectService.addNewProject(projectDTO);
+    public void addNewProject(@Valid @RequestBody ProjectCreateOrUpdateDTO projectCreateOrUpdateDTOsend) {
```
Comment (iv21dk) [inline src/main/java/com/springweb/dv_spring_web_mongo/controller/ProjectController.java]: `projectCreateOrUpdateDTO` without `send` word

**Review by iv21dk — CHANGES_REQUESTED** [review]

**Comment by iv21dk** [comment]
Approved
